- hosts: local
  vars:
    docker_image: "{{ docker_image | default('raginimetlapalli/calculator') }}"
    docker_tag:   "{{ docker_tag | default('latest') }}"
    container_name: Calculator

  tasks:
    - name: Ensure curl present (for get.docker.com)
      apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Ensure Docker installed (quick install via convenience script)
      shell: |
        if ! command -v docker >/dev/null 2>&1; then
          curl -fsSL https://get.docker.com | sh
        fi
      args:
        warn: false
      become: yes

    - name: Add current user to docker group (so non-root can run docker)
      user:
        name: "{{ ansible_user | default(lookup('env','USER')) }}"
        groups: docker
        append: yes
      become: yes
      ignore_errors: yes

    - name: Pull docker image
      command: docker pull {{ docker_image }}:{{ docker_tag }}

    - name: Stop and remove old container (if any)
      shell: docker rm -f {{ container_name }} || true

    - name: Run container (detached, keep tty and stdin open)
      shell: docker run -d --name {{ container_name }} -it --restart unless-stopped {{ docker_image }}:{{ docker_tag }}
